//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CargaBloomberg.WinLoadPreciosBloomberg.WcfSrvCargaPrecBloomRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfSrvCargaPrecBloomRef.ICargarPreciosBloomSrv")]
    public interface ICargarPreciosBloomSrv {
        
        // CODEGEN: Generating message contract since the wrapper name (DownloadRequest) of message DownloadRequest does not match the default value (DownloadFile)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICargarPreciosBloomSrv/DownloadFile", ReplyAction="http://tempuri.org/ICargarPreciosBloomSrv/DownloadFileResponse")]
        CargaBloomberg.WinLoadPreciosBloomberg.WcfSrvCargaPrecBloomRef.RemoteFileInfo DownloadFile(CargaBloomberg.WinLoadPreciosBloomberg.WcfSrvCargaPrecBloomRef.DownloadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICargarPreciosBloomSrv/DownloadFile", ReplyAction="http://tempuri.org/ICargarPreciosBloomSrv/DownloadFileResponse")]
        System.Threading.Tasks.Task<CargaBloomberg.WinLoadPreciosBloomberg.WcfSrvCargaPrecBloomRef.RemoteFileInfo> DownloadFileAsync(CargaBloomberg.WinLoadPreciosBloomberg.WcfSrvCargaPrecBloomRef.DownloadRequest request);
        
        // CODEGEN: Generating message contract since the operation UploadFile is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICargarPreciosBloomSrv/UploadFile", ReplyAction="http://tempuri.org/ICargarPreciosBloomSrv/UploadFileResponse")]
        CargaBloomberg.WinLoadPreciosBloomberg.WcfSrvCargaPrecBloomRef.UploadFileResponse UploadFile(CargaBloomberg.WinLoadPreciosBloomberg.WcfSrvCargaPrecBloomRef.RemoteFileInfo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICargarPreciosBloomSrv/UploadFile", ReplyAction="http://tempuri.org/ICargarPreciosBloomSrv/UploadFileResponse")]
        System.Threading.Tasks.Task<CargaBloomberg.WinLoadPreciosBloomberg.WcfSrvCargaPrecBloomRef.UploadFileResponse> UploadFileAsync(CargaBloomberg.WinLoadPreciosBloomberg.WcfSrvCargaPrecBloomRef.RemoteFileInfo request);
        
        // CODEGEN: Generating message contract since the operation CargarPreciosTmp is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICargarPreciosBloomSrv/CargarPreciosTmp", ReplyAction="http://tempuri.org/ICargarPreciosBloomSrv/CargarPreciosTmpResponse")]
        CargaBloomberg.WinLoadPreciosBloomberg.WcfSrvCargaPrecBloomRef.CargarPreciosTmpResponse CargarPreciosTmp(CargaBloomberg.WinLoadPreciosBloomberg.WcfSrvCargaPrecBloomRef.RemoteFileInfo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICargarPreciosBloomSrv/CargarPreciosTmp", ReplyAction="http://tempuri.org/ICargarPreciosBloomSrv/CargarPreciosTmpResponse")]
        System.Threading.Tasks.Task<CargaBloomberg.WinLoadPreciosBloomberg.WcfSrvCargaPrecBloomRef.CargarPreciosTmpResponse> CargarPreciosTmpAsync(CargaBloomberg.WinLoadPreciosBloomberg.WcfSrvCargaPrecBloomRef.RemoteFileInfo request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DownloadRequest", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DownloadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Filename;
        
        public DownloadRequest() {
        }
        
        public DownloadRequest(string Filename) {
            this.Filename = Filename;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoteFileInfo", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RemoteFileInfo {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string Filename;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public long Length;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream FileByteStream;
        
        public RemoteFileInfo() {
        }
        
        public RemoteFileInfo(string Filename, long Length, System.IO.Stream FileByteStream) {
            this.Filename = Filename;
            this.Length = Length;
            this.FileByteStream = FileByteStream;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadFileResponse {
        
        public UploadFileResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CargarPreciosTmpResponse {
        
        public CargarPreciosTmpResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICargarPreciosBloomSrvChannel : CargaBloomberg.WinLoadPreciosBloomberg.WcfSrvCargaPrecBloomRef.ICargarPreciosBloomSrv, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CargarPreciosBloomSrvClient : System.ServiceModel.ClientBase<CargaBloomberg.WinLoadPreciosBloomberg.WcfSrvCargaPrecBloomRef.ICargarPreciosBloomSrv>, CargaBloomberg.WinLoadPreciosBloomberg.WcfSrvCargaPrecBloomRef.ICargarPreciosBloomSrv {
        
        public CargarPreciosBloomSrvClient() {
        }
        
        public CargarPreciosBloomSrvClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CargarPreciosBloomSrvClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CargarPreciosBloomSrvClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CargarPreciosBloomSrvClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CargaBloomberg.WinLoadPreciosBloomberg.WcfSrvCargaPrecBloomRef.RemoteFileInfo CargaBloomberg.WinLoadPreciosBloomberg.WcfSrvCargaPrecBloomRef.ICargarPreciosBloomSrv.DownloadFile(CargaBloomberg.WinLoadPreciosBloomberg.WcfSrvCargaPrecBloomRef.DownloadRequest request) {
            return base.Channel.DownloadFile(request);
        }
        
        public long DownloadFile(ref string Filename, out System.IO.Stream FileByteStream) {
            CargaBloomberg.WinLoadPreciosBloomberg.WcfSrvCargaPrecBloomRef.DownloadRequest inValue = new CargaBloomberg.WinLoadPreciosBloomberg.WcfSrvCargaPrecBloomRef.DownloadRequest();
            inValue.Filename = Filename;
            CargaBloomberg.WinLoadPreciosBloomberg.WcfSrvCargaPrecBloomRef.RemoteFileInfo retVal = ((CargaBloomberg.WinLoadPreciosBloomberg.WcfSrvCargaPrecBloomRef.ICargarPreciosBloomSrv)(this)).DownloadFile(inValue);
            Filename = retVal.Filename;
            FileByteStream = retVal.FileByteStream;
            return retVal.Length;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CargaBloomberg.WinLoadPreciosBloomberg.WcfSrvCargaPrecBloomRef.RemoteFileInfo> CargaBloomberg.WinLoadPreciosBloomberg.WcfSrvCargaPrecBloomRef.ICargarPreciosBloomSrv.DownloadFileAsync(CargaBloomberg.WinLoadPreciosBloomberg.WcfSrvCargaPrecBloomRef.DownloadRequest request) {
            return base.Channel.DownloadFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<CargaBloomberg.WinLoadPreciosBloomberg.WcfSrvCargaPrecBloomRef.RemoteFileInfo> DownloadFileAsync(string Filename) {
            CargaBloomberg.WinLoadPreciosBloomberg.WcfSrvCargaPrecBloomRef.DownloadRequest inValue = new CargaBloomberg.WinLoadPreciosBloomberg.WcfSrvCargaPrecBloomRef.DownloadRequest();
            inValue.Filename = Filename;
            return ((CargaBloomberg.WinLoadPreciosBloomberg.WcfSrvCargaPrecBloomRef.ICargarPreciosBloomSrv)(this)).DownloadFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CargaBloomberg.WinLoadPreciosBloomberg.WcfSrvCargaPrecBloomRef.UploadFileResponse CargaBloomberg.WinLoadPreciosBloomberg.WcfSrvCargaPrecBloomRef.ICargarPreciosBloomSrv.UploadFile(CargaBloomberg.WinLoadPreciosBloomberg.WcfSrvCargaPrecBloomRef.RemoteFileInfo request) {
            return base.Channel.UploadFile(request);
        }
        
        public void UploadFile(string Filename, long Length, System.IO.Stream FileByteStream) {
            CargaBloomberg.WinLoadPreciosBloomberg.WcfSrvCargaPrecBloomRef.RemoteFileInfo inValue = new CargaBloomberg.WinLoadPreciosBloomberg.WcfSrvCargaPrecBloomRef.RemoteFileInfo();
            inValue.Filename = Filename;
            inValue.Length = Length;
            inValue.FileByteStream = FileByteStream;
            CargaBloomberg.WinLoadPreciosBloomberg.WcfSrvCargaPrecBloomRef.UploadFileResponse retVal = ((CargaBloomberg.WinLoadPreciosBloomberg.WcfSrvCargaPrecBloomRef.ICargarPreciosBloomSrv)(this)).UploadFile(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CargaBloomberg.WinLoadPreciosBloomberg.WcfSrvCargaPrecBloomRef.UploadFileResponse> CargaBloomberg.WinLoadPreciosBloomberg.WcfSrvCargaPrecBloomRef.ICargarPreciosBloomSrv.UploadFileAsync(CargaBloomberg.WinLoadPreciosBloomberg.WcfSrvCargaPrecBloomRef.RemoteFileInfo request) {
            return base.Channel.UploadFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<CargaBloomberg.WinLoadPreciosBloomberg.WcfSrvCargaPrecBloomRef.UploadFileResponse> UploadFileAsync(string Filename, long Length, System.IO.Stream FileByteStream) {
            CargaBloomberg.WinLoadPreciosBloomberg.WcfSrvCargaPrecBloomRef.RemoteFileInfo inValue = new CargaBloomberg.WinLoadPreciosBloomberg.WcfSrvCargaPrecBloomRef.RemoteFileInfo();
            inValue.Filename = Filename;
            inValue.Length = Length;
            inValue.FileByteStream = FileByteStream;
            return ((CargaBloomberg.WinLoadPreciosBloomberg.WcfSrvCargaPrecBloomRef.ICargarPreciosBloomSrv)(this)).UploadFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CargaBloomberg.WinLoadPreciosBloomberg.WcfSrvCargaPrecBloomRef.CargarPreciosTmpResponse CargaBloomberg.WinLoadPreciosBloomberg.WcfSrvCargaPrecBloomRef.ICargarPreciosBloomSrv.CargarPreciosTmp(CargaBloomberg.WinLoadPreciosBloomberg.WcfSrvCargaPrecBloomRef.RemoteFileInfo request) {
            return base.Channel.CargarPreciosTmp(request);
        }
        
        public void CargarPreciosTmp(string Filename, long Length, System.IO.Stream FileByteStream) {
            CargaBloomberg.WinLoadPreciosBloomberg.WcfSrvCargaPrecBloomRef.RemoteFileInfo inValue = new CargaBloomberg.WinLoadPreciosBloomberg.WcfSrvCargaPrecBloomRef.RemoteFileInfo();
            inValue.Filename = Filename;
            inValue.Length = Length;
            inValue.FileByteStream = FileByteStream;
            CargaBloomberg.WinLoadPreciosBloomberg.WcfSrvCargaPrecBloomRef.CargarPreciosTmpResponse retVal = ((CargaBloomberg.WinLoadPreciosBloomberg.WcfSrvCargaPrecBloomRef.ICargarPreciosBloomSrv)(this)).CargarPreciosTmp(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CargaBloomberg.WinLoadPreciosBloomberg.WcfSrvCargaPrecBloomRef.CargarPreciosTmpResponse> CargaBloomberg.WinLoadPreciosBloomberg.WcfSrvCargaPrecBloomRef.ICargarPreciosBloomSrv.CargarPreciosTmpAsync(CargaBloomberg.WinLoadPreciosBloomberg.WcfSrvCargaPrecBloomRef.RemoteFileInfo request) {
            return base.Channel.CargarPreciosTmpAsync(request);
        }
        
        public System.Threading.Tasks.Task<CargaBloomberg.WinLoadPreciosBloomberg.WcfSrvCargaPrecBloomRef.CargarPreciosTmpResponse> CargarPreciosTmpAsync(string Filename, long Length, System.IO.Stream FileByteStream) {
            CargaBloomberg.WinLoadPreciosBloomberg.WcfSrvCargaPrecBloomRef.RemoteFileInfo inValue = new CargaBloomberg.WinLoadPreciosBloomberg.WcfSrvCargaPrecBloomRef.RemoteFileInfo();
            inValue.Filename = Filename;
            inValue.Length = Length;
            inValue.FileByteStream = FileByteStream;
            return ((CargaBloomberg.WinLoadPreciosBloomberg.WcfSrvCargaPrecBloomRef.ICargarPreciosBloomSrv)(this)).CargarPreciosTmpAsync(inValue);
        }
    }
}
